export default {
    a: 'alligator',
    b: 'bear',
    c: 'cow',
    d: 'dog',
    e: 'elephant',
    f: 'frog',
    g: 'goat',
    h: 'horse',
    i: 'impala',
    j: 'jaguar',
    k: 'kingfisher',
    l: 'lion',
    m: 'monkey',
    n: 'nightingale',
    o: 'owl',
    p: 'pig',
    q: 'quail',
    r: 'rabbit',
    s: 'sheep',
    t: 'turkey',
    u: 'umbrella',
    v: 'vulture',
    w: 'whale',
    x: 'x-ray fish',
    y: 'yak',
    z: 'zebra'
  };
