export default {
    a: 'apple',
    b: 'book',
    c: 'car',
    d: 'dog',
    e: 'elephant',
    f: 'fish',
    g: 'goat',
    h: 'hat',
    i: 'ice cream',
    j: 'jelly',
    k: 'kite',
    l: 'lion',
    m: 'monkey',
    n: 'nest',
    o: 'owl',
    p: 'pool',
    q: 'quiet',
    r: 'road',
    s: 'sun',
    t: 'tree',
    u: 'umbrella',
    v: 'vine',
    w: 'worm',
    x: 'xylophone',
    y: 'yes',
    z: 'zoo'
  };
